### ISSUE TITLE
OutLook And OneNote Crash

### ISSUE THREAD

**Issue by mgcnrx11** [goodbest/OfficeThinner#2]
Here are the Output of Thinner Script:

```
Thinning Fonts, it saves you ~1.4G space
mv: rename /Applications/Microsoft Outlook.app/Contents/Resources/DFonts to /Users/USERNAME/Desktop/OfficeThinnerBackup/Microsoft Outlook/Contents/Resources/DFonts: No such file or directory
mv: rename /Applications/Microsoft OneNote.app/Contents/Resources/DFonts to /Users/USERNAME/Desktop/OfficeThinnerBackup/Microsoft OneNote/Contents/Resources/DFonts: No such file or directory
Thinning Proofing Tools, it saves you ~1.5G space
Thinning MicrosoftOffice.framework, it saves you ~0.8G space

Office Thinning Complete.
The duplicate files are backed up at /Users/USERNAME/Desktop/OfficeThinnerBackup/

If everything is OK, you may delete them. But the choice is yours.
You may have to re-run this script after you install Microsoft Office updates
```

It seems like the "IF" statement for DFont of Font doesn't work??

And when I open OneNote, it keep crash over and over.

OutLook is like this Image.
<img width="847" alt="2015-12-12 11 09 01" src="https://cloud.githubusercontent.com/assets/1214823/11762546/5d6f8ad2-a125-11e5-9c27-38044feddea7.png">

Version 15.17

**Comment by goodbest** [comment]
First things first, I suggest you do one of the following operation to make Outlook and OneNote work again.
- You may manually recover with the backup files on Desktop
- or, you may download and install the official updates from https://support.microsoft.com/en-us/kb/3119518
- or, you may re-install Office again.

Then comes the discussion about your error output.
Can you confirm that all of your 5 .app are version 15.17 before you run this script?
In my machine, `DFonts` folder exists in all the 5 apps with version 15.17, but they don't exist with version 15.16.
One reason of this error output is that your Word.app is 15.17, but your Outlook and OneNote are still 15.16 (due to update errors, etc.)

**Comment by mgcnrx11** [comment]
yeah, you are right. I might have update errors and cause outlook and one note still in 15.16.

anyway, thanks for the reply. i'll try later.

**Comment by goodbest** [comment]
So I'll close this issue if that solves your problem.
